"""empty message

Revision ID: 44fa312a2bd
Revises: 44b0e2a6aa5
Create Date: 2014-11-12 20:30:34.829065

"""

# revision identifiers, used by Alembic.
revision = '44fa312a2bd'
down_revision = '44b0e2a6aa5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
